# Generated by Django 3.1.5 on 2021-01-23 13:07

from django.db import migrations, models
import sorl.thumbnail.fields
import yashyl_ada_backend.apps.projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('url', models.URLField()),
                ('image', sorl.thumbnail.fields.ImageField(default='img/image_not_found.png', upload_to=yashyl_ada_backend.apps.projects.models.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
